### ISSUE TITLE
Suggestion: Home Page Format

### ISSUE THREAD

**Issue by CL3000** [jbaum012/sports#4]
For the home page ("Sports" tab at the top), instead of listing Week 1 above Week 2, you could put Week 2 above Week 1, Week 3 above Week 2, and so on, so the current week is always on top. The way it's formatted now, you kinda have to scroll down to get to the current week when we get later into the season.

An alternative suggestion would be just to have a "Previous Weeks" drop-down that had all the previous weeks' drop-downs listed (i.e. just "Previous Weeks" and the current week is showing on the home page. When you click on "Previous Weeks" a drop-down shows Week 1, Week 2, Week 3, etc. and when you click on a specific week, that drops down and shows the data from that week.)

**Comment by jbaum012** [comment]
For some reason the sorting has been really difficult to fix, but I totally agree with your suggestion.  I was also thinking about changing the display so it was more square shaped and less horizontal row shaped.  The issue is that on mobile you need to scroll which is silly.  I will toy with some different layouts

**Comment by jbaum012** [comment]
Sorting is fixed!
